export const CATEGORY_GROUPS: Record<string, string[]> = {
  nutrition: [
    "calorie", "calories", "caloric", "macro", "macros", "macronutrient",
    "micronutrient", "protein", "carb", "carbs", "carbohydrate", "fat", "fats",
    "fiber", "fibre", "nutrition", "nutrient", "nutrients", "nutritious",
    "diet", "dieting", "dietary", "vitamin", "vitamins", "mineral", "minerals",
    "nutri", "weight", "lose", "loss", "slim", "slimming", "bmi", "food",
    "foods", "meal", "meals", "eat", "eating", "recipe", "recipes", "portion",
    "portions", "ingredient", "ingredients", "glucose", "sugar", "counter",
    "tracker", "tracking", "log", "logging", "diary", "journal", "keto",
    "ketogenic", "intermittent", "fasting", "fast", "vegan", "vegetarian",
    "paleo", "gluten", "dairy", "allergy", "scan", "barcode", "water",
    "hydration", "intake", "deficit", "surplus", "tdee", "bmr", "snack",
    "snacks", "breakfast", "lunch", "dinner", "serving", "servings",
    "sodium", "potassium", "iron", "calcium", "omega", "supplement",
    "supplements", "shake", "prep", "batch", "restaurant", "organic",
    "whole", "plant", "cholesterol", "saturated", "trans", "net",
    "calculator", "count", "counted", "goal", "goals", "target",
  ],

  fitness: [
    "fitness", "workout", "workouts", "exercise", "exercises", "gym",
    "training", "cardio", "strength", "muscle", "muscles", "active",
    "activity", "activities", "run", "running", "step", "steps", "walk",
    "walking", "yoga", "pilates", "hiit", "crossfit", "powerlifting",
    "bodyweight", "rep", "reps", "set", "sets", "routine", "routines",
    "program", "programs", "stretch", "stretching", "cycling", "swim",
    "swimming", "rowing", "squat", "deadlift", "bench", "press", "curl",
    "plank", "ab", "abs", "core", "glute", "glutes", "leg", "legs",
    "arms", "chest", "back", "shoulder", "shoulders", "bicep", "tricep",
    "interval", "beginner", "intermediate", "advanced", "home", "outdoor",
    "marathon", "race", "pullup", "pushup", "pushups", "pullups", "lunge",
    "lunges", "burpee", "burpees", "kettlebell", "dumbbell", "barbell",
    "band", "treadmill", "elliptical", "mile", "pace", "speed", "burn",
    "burned", "burning", "trainer", "coach", "personal", "tone", "toning",
    "lean", "bulk", "bulking", "plyometric", "functional", "resistance",
    "flexibility", "mobility", "recovery", "foam", "roll", "sport", "sports",
    "log", "tracker", "calorie", "calories",
  ],

  health: [
    "health", "healthy", "wellness", "wellbeing", "body", "heart",
    "blood", "pressure", "oxygen", "pulse", "period", "menstrual", "cycle",
    "ovulation", "pregnancy", "prenatal", "baby", "symptom", "symptoms",
    "medicine", "medication", "pill", "pills", "dose", "dosage", "doctor",
    "appointment", "hospital", "clinic", "chronic", "diabetes", "cholesterol",
    "thyroid", "hormones", "immune", "allergy", "skin", "acne", "dental",
    "teeth", "tracker", "tracking", "monitor", "monitoring", "vitals",
    "wearable", "watch", "sleep", "stress", "recovery", "hrv", "vision",
    "eye", "eyes", "posture", "hydration", "fertility", "bmi", "pharmacy",
    "prescription", "aging", "longevity", "weight", "bmi",
  ],

  finance: [
    "budget", "budgeting", "money", "expense", "expenses", "spend",
    "spending", "saving", "savings", "invest", "investing", "investment",
    "bank", "banking", "bill", "bills", "debt", "income", "financial",
    "cash", "payment", "payments", "tax", "taxes", "wallet", "credit",
    "debit", "card", "loan", "mortgage", "rent", "paycheck", "salary",
    "net", "worth", "portfolio", "stock", "stocks", "crypto",
    "cryptocurrency", "bitcoin", "ethereum", "forex", "trading", "dividend",
    "retirement", "pension", "insurance", "receipt", "receipts", "track",
    "tracker", "goal", "goals", "emergency", "fund", "401k", "ira", "roth",
    "payroll", "asset", "liability", "interest", "rate", "apr", "apy",
    "account", "checking", "transfer", "wire", "split", "owe", "lend",
    "borrow", "subscription", "subscriptions", "fee", "fees", "compound",
    "real estate", "property", "freelance", "invoice", "invoicing",
    "profit", "loss", "cashflow", "net worth",
  ],

  productivity: [
    "task", "tasks", "todo", "todos", "note", "notes", "reminder",
    "reminders", "schedule", "scheduling", "calendar", "plan", "planning",
    "project", "projects", "habit", "habits", "focus", "organize",
    "organization", "list", "lists", "checklist", "checklists", "deadline",
    "deadlines", "meeting", "meetings", "time", "management", "pomodoro",
    "timer", "block", "blocking", "distraction", "gtd", "kanban", "board",
    "workflow", "workspace", "collaborate", "team", "teams", "assign",
    "priority", "priorities", "inbox", "journal", "journaling", "writing",
    "document", "documents", "template", "templates", "automation",
    "sprint", "agile", "scrum", "email", "delegate", "review", "weekly",
    "daily", "capture", "tag", "tags", "label", "labels", "folder",
    "folders", "search", "offline", "sync", "cloud", "markdown",
    "shortcut", "shortcuts", "widget", "widgets", "voice", "dictate",
    "read", "highlight", "annotation", "clip", "save",
  ],

  travel: [
    "travel", "traveling", "trip", "trips", "flight", "flights", "hotel",
    "hotels", "booking", "book", "navigate", "navigation", "gps",
    "destination", "destinations", "vacation", "vacations", "tour",
    "tours", "itinerary", "itineraries", "passport", "visa", "currency",
    "exchange", "map", "maps", "route", "routes", "transport",
    "transportation", "taxi", "car", "rental", "train", "bus", "ferry",
    "hostel", "airbnb", "review", "reviews", "guide", "guides", "language",
    "translate", "offline", "explore", "country", "countries", "city",
    "cities", "airport", "airline", "airlines", "cheap", "budget",
    "backpacker", "luxury", "resort", "camping", "hiking", "restaurant",
    "food", "museum", "attraction", "sightseeing", "packing", "luggage",
    "insurance", "wifi", "timezone", "solo", "family", "road", "cruise",
    "ship", "boat", "beach", "mountain",
  ],

  education: [
    "learn", "learning", "study", "studying", "quiz", "quizzes",
    "course", "courses", "lesson", "lessons", "language", "languages",
    "practice", "practicing", "skill", "skills", "tutor", "tutoring",
    "flashcard", "flashcards", "test", "tests", "exam", "exams",
    "school", "college", "university", "math", "science", "history",
    "english", "reading", "writing", "spelling", "vocabulary", "grammar",
    "kid", "kids", "child", "children", "toddler", "kindergarten",
    "coding", "programming", "certificate", "certification", "degree",
    "lecture", "lectures", "ebook", "homeschool", "curriculum",
    "memory", "memorize", "logic", "reasoning", "game", "gamification",
    "reward", "badge", "achievement", "progress", "streak", "streaks",
    "teacher", "parent", "elementary", "sat", "act", "gre", "gmat",
    "ielts", "toefl", "speak", "speaking", "pronunciation", "listen",
    "listening", "comprehension", "sign language", "art", "drawing",
  ],

  meditation: [
    "meditation", "meditate", "mindful", "mindfulness", "calm", "calming",
    "stress", "anxiety", "anxious", "sleep", "sleeping", "breathe",
    "breathing", "relax", "relaxation", "relaxing", "mental", "mood",
    "panic", "depression", "therapy", "therapist", "counseling",
    "gratitude", "affirmation", "affirmations", "positive", "happiness",
    "happy", "peace", "peaceful", "quiet", "silence", "sound", "sounds",
    "noise", "white", "ambient", "guided", "guide", "body", "scan",
    "visualization", "mantra", "journal", "journaling", "cbt", "cognitive",
    "self", "care", "compassion", "burnout", "trauma", "ptsd", "addiction",
    "recovery", "sobriety", "anger", "management", "forgiveness",
    "manifestation", "spiritual", "soul", "chakra", "chakras", "frequency",
    "binaural", "insomnia", "restless", "grief", "loss", "wellbeing",
    "emotion", "emotions", "emotional", "overthinking", "worry", "fear",
  ],

  photo: [
    "photo", "photos", "camera", "picture", "pictures", "image", "images",
    "filter", "filters", "edit", "editing", "editor", "snap", "selfie",
    "selfies", "collage", "collages", "video", "videos", "scan", "scanning",
    "document", "portrait", "landscape", "raw", "jpeg", "png", "gif",
    "story", "stories", "reel", "reels", "watermark", "crop", "resize",
    "background", "remove", "erase", "enhance", "color", "tone",
    "brightness", "contrast", "exposure", "hdr", "panorama", "burst",
    "slow", "motion", "timelapse", "slideshow", "album", "albums",
    "gallery", "organize", "share", "print", "prints", "retouch",
    "retouching", "blur", "bokeh", "night", "zoom", "wide", "professional",
    "pro", "frame", "frames", "border", "sticker", "stickers",
    "meme", "text", "caption", "face", "beauty", "skin", "restore",
    "vintage", "upscale", "animation", "animated", "collage",
  ],

  social: [
    "social", "chat", "message", "messages", "messaging", "connect",
    "friend", "friends", "follow", "followers", "dating", "date",
    "match", "matches", "network", "community", "communities", "group",
    "groups", "forum", "forums", "post", "posts", "share", "like",
    "comment", "comments", "live", "stream", "streaming", "broadcast",
    "video", "call", "calls", "voice", "profile", "bio", "relationship",
    "relationships", "couple", "partner", "discover", "explore",
    "anonymous", "private", "privacy", "notification", "notifications",
    "inbox", "direct", "story", "stories", "trend", "trending",
    "hashtag", "hashtags", "mention", "tag", "creator", "content",
    "influencer", "reaction", "emoji", "status",
  ],

  music: [
    "music", "song", "songs", "playlist", "playlists", "audio", "listen",
    "listening", "podcast", "podcasts", "stream", "streaming", "beat",
    "beats", "tune", "tunes", "instrument", "instruments", "guitar",
    "piano", "drum", "drums", "chord", "chords", "tab", "tabs",
    "lyric", "lyrics", "karaoke", "sing", "singing", "record",
    "recording", "mix", "mixing", "sound", "sounds", "ringtone",
    "alarm", "metronome", "tuner", "dj", "rap", "hip", "hop", "jazz",
    "classical", "ambient", "compose", "composer", "composition",
    "note", "notes", "sheet", "scale", "scales", "theory", "ear",
    "training", "interval", "intervals", "progression", "loop", "loops",
    "sample", "samples", "effect", "effects", "reverb", "delay",
    "equalizer", "eq", "tempo", "bpm", "vocal", "vocals", "ukulele",
    "violin", "flute", "saxophone", "bass", "treble", "download",
    "album", "albums", "artist", "artists", "concert", "radio", "station",
  ],

  shopping: [
    "shop", "shopping", "buy", "buying", "sale", "sales", "deal", "deals",
    "coupon", "coupons", "discount", "discounts", "price", "prices",
    "compare", "comparison", "review", "reviews", "product", "products",
    "wishlist", "cart", "checkout", "order", "orders", "track", "delivery",
    "shipping", "refund", "return", "brand", "brands", "clothes",
    "clothing", "fashion", "shoes", "accessories", "beauty", "cosmetics",
    "grocery", "groceries", "supermarket", "online", "marketplace",
    "secondhand", "thrift", "used", "luxury", "designer", "size", "fit",
    "save", "notify", "alert", "clearance", "outlet", "gift", "gifts",
    "subscribe", "subscription", "local", "handmade", "artisan", "rent",
    "rental", "sell", "selling", "listing", "swap", "trade", "auction",
    "bid", "bidding", "cashback", "reward", "points", "loyalty",
  ],

  weather: [
    "weather", "forecast", "rain", "raining", "sunny", "sunshine", "cloud",
    "clouds", "cloudy", "temperature", "humid", "humidity", "wind",
    "snow", "snowing", "storm", "storms", "lightning", "thunder",
    "hurricane", "tornado", "alert", "alerts", "radar", "hourly",
    "daily", "weekly", "climate", "uv", "index", "air", "quality",
    "pollen", "allergy", "outdoor", "activities", "commute", "drive",
    "hiking", "garden", "gardening", "plant", "current", "live",
    "notification", "severe", "warning", "watch", "satellite",
    "feels", "wind chill", "heat", "dewpoint", "visibility",
    "moon", "sun", "rise", "set", "tide", "season", "spring", "summer",
    "fall", "winter", "snow", "ice", "fog", "foggy", "dew", "frost",
  ],
};
